# Version of Docker-compose
version: '3.9'
services:
  # Add the node-js service
  backend:
  # Location to the node.js dockerfile
    build: 
      context: ./backend
        # Name of the dockerfile
      dockerfile: Dockerfile
    container_name: backend-b
    ports:
       # Host port:Container port
      - '8080:8080'
    environment:
      FRONT_URL: "http://localhost:3000"
  frontend:
  # Location to the react.js dockerfile
    build: 
      context: ./frontend
        # Name of the dockerfile
      dockerfile: Dockerfile
    container_name: frontend-f
    ports:
     # Host port:Container port
      - '3000:3000'
    environment:
       REACT_APP_API_URL: "http://localhost:8080"
    stdin_open: true